### ISSUE TITLE
Support kubernetes version > v1.20.0

### ISSUE THREAD

**Issue by Frisch12** [cluster-api-provider-hcloud/cluster-api-provider-hcloud#104]
**What steps did you take and what happened:**
`clusterctl init --infrastructure hcloud:v0.1.4` does not work with kubernetes version > v1.20.0 
Error message:
```
Error: failed to get provider components for the "hcloud:v0.1.4" provider: failed to set the TargetNamespace on the components: converting (v1beta1.ValidatingWebhookConfiguration) to (v1.ValidatingWebhookConfiguration): unknown conversion
```

**Anything else you would like to add:**
Components should be updated to api-version v1. Automatic conversion does not work correctly.

**Environment:**

- Cluster-api version: v0.4.1
- Cluster-api-provider-hcloud version: v0.1.4
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
```
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

**Comment by batistein** [comment]
Closed due to archiving! Please checkout the new repo [https://github.com/syself/cluster-api-provider-hetzner](https://github.com/syself/cluster-api-provider-hetzner)

Kubernetes support is there for v1.22 and v1.23
