### ISSUE TITLE
IPv6 to IPv4 translation for Metallb

### ISSUE THREAD

**Issue by batistein** [cluster-api-provider-hcloud/cluster-api-provider-hcloud#37]
**User Story**

As a user I would like to access the cluster via IPv6 and IPv4.

**Detailed Description**

We need to find a solution to translate IPv6 to IPv4. This solution i found on Hetzner Community: https://community.hetzner.com/tutorials/install-kubernetes-cluster#step-22---configure-ipv6-to-ipv4-translation-optional

**Comment by toonsevrin** [comment]
Hi Sven, for your interest: [Dual stack is in Alpha](https://kubernetes.io/docs/concepts/services-networking/dual-stack/)

**Comment by batistein** [comment]
You're right. However, debugging is then twice as time-consuming. At the moment I would say we'd rather stay with IPv4 internally and let the load balancer do the translation... But in anyway, it's good to know that dual stack get's some traction. 
But we could definitely implement this option for all those who want to have dual stack. Feel free to make a PR.

**Comment by toonsevrin** [comment]
Gotcha! Makes sense. My k8s dual stack knowledge is a bit too lacking right now to pr this myself :)
